version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: fintech-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: fintech_forecasting
    volumes:
      - mongodb_data:/data/db
    networks:
      - fintech-network

  backend:
    build: ./backend
    container_name: fintech-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/fintech_forecasting
      FLASK_ENV: production
    depends_on:
      - mongodb
    networks:
      - fintech-network

  frontend:
    build: ./frontend
    container_name: fintech-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - fintech-network

volumes:
  mongodb_data:

networks:
  fintech-network:
    driver: bridge
